import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`bg-black flex w-full flex-col h-[100dvh]`}
       >
         <div className="flex-1 overflow-hidden">
         <ToastContainer position="top-right" autoClose={2000} />
           {children}
         </div>
      </body>
    </html>
  );
}
